"""Changes 2024-08-01T20:27:27Z

Revision ID: 92654e69e947
Revises: 
Create Date: 2024-08-01 23:27:28.612321

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # added
from alembic import op

from models import *

# revision identifiers, used by Alembic.
revision: str = '92654e69e947'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_number', sqlmodel.sql.sqltypes.AutoString(
                        length=MAX_ORDER_NUMBER_LENGTH), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_os_order_order_number'),
                    'os_order', ['order_number'], unique=True)
    op.create_table('os_serial_number',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('serial_number_code', sqlmodel.sql.sqltypes.AutoString(
                        length=MAX_SERIAL_NUMBER_CODE_LENGTH), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_os_serial_number_serial_number_code'),
                    'os_serial_number', ['serial_number_code'], unique=True)
    op.create_table('os_sku',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sku_code', sqlmodel.sql.sqltypes.AutoString(
                        length=MAX_SKU_CODE_LENGTH), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_os_sku_sku_code'),
                    'os_sku', ['sku_code'], unique=True)
    op.create_table('os_sku_characteristics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sku_characteristics_weight',
                              sa.Float(), nullable=True),
                    sa.Column('sku_characteristics_volume',
                              sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('os_sku_characteristics')
    op.drop_index(op.f('ix_os_sku_sku_code'), table_name='os_sku')
    op.drop_table('os_sku')
    op.drop_index(op.f('ix_os_serial_number_serial_number_code'),
                  table_name='os_serial_number')
    op.drop_table('os_serial_number')
    op.drop_index(op.f('ix_os_order_order_number'), table_name='os_order')
    op.drop_table('os_order')
    # ### end Alembic commands ###
