"""Initial database structure

Revision ID: c94f0df4c2c5
Revises: 
Create Date: 2024-07-28 13:17:03.292497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added 


# revision identifiers, used by Alembic.
revision: str = 'c94f0df4c2c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('os_model_number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_model_number_code'), 'os_model_number', ['code'], unique=True)
    op.create_table('os_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_order_number'), 'os_order', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_os_order_number'), table_name='os_order')
    op.drop_table('os_order')
    op.drop_index(op.f('ix_os_model_number_code'), table_name='os_model_number')
    op.drop_table('os_model_number')
    # ### end Alembic commands ###
